#!/bin/bash

echo 'auto lo' > /etc/network/interfaces.wifi

echo 'iface lo inet loopback' >> /etc/network/interfaces.wifi

echo 'iface eth0 inet dhcp' >> /etc/network/interfaces.wifi

echo 'allow-hotplug wlan0' >> /etc/network/interfaces.wifi

echo 'iface wlan0 inet dhcp' >> /etc/network/interfaces.wifi

echo "  wpa-ssid \"$1\"" >> /etc/network/interfaces.wifi

echo "  wpa-psk \"$2\"" >> /etc/network/interfaces.wifi

cp /etc/network/interfaces.wifi /etc/network/interfaces

ifdown wlan0
sleep 1
service hostapd stop
service udhcpd stop

ifup wlan0

exit 0
